spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chattest
    username: boris
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    root: info